### ISSUE TITLE
Current Division or Time Division?

### ISSUE THREAD

**Issue by djangodemetri** [glazet/QuadEVCharger#25]
Facts:
Minimum of 8A for Rivians

Assumptions:
Cars will take the majority of power if allowed

Current Division:
Pros:
More effective usage of current and charge points
Immediate charge
Less heat (H=kI^2)

Cons:
Complex
Expensive
Small charge per vehicle
Battery getting to charging temperature

Time Division:
Pros:
Simpler 
Cheaper
Better battery charging curve (assumption)

Cons:
No immediate charge
Not using ports or amperage fully 
More heat

Future:
Download apps to test minimum amperage
What is the minimum temperature for the battery to charge?

**Comment by neilh10** [comment]
Gosh from reading this, what is the  technical question you are phrasing? and trying to track.
The customer issue is plugging in and getting charge till battery full, with up to 4 vehicles charging, and getting it in the shortest period possible.
The technical optimization is to use the 40A from the EVSE/grid as fully as possible.  The J1772 protocol "Charge Point" language is that the PWM signal advertises the current the vehicle can take, however the vehicle takes the charge it can handle up to the advertised limit, OR up to when its battery is fully charged.  My understanding is that generally batteries are better on a slower charge so the vehicles may not take all the charge if they are offered it.
To me optimally "sharing the current" on up to 4 vehicles taking a charge, is likely to lead to all vehicles getting a full charge in the shorted period. The optimally sharing the current means it requires to monitor the actual current that is being drawn. A smart algorithm is one that can detect what the vehicle is taking, and change the PWM to what is being "advertised" across the plugged in vehicles, however that is software and maybe too complicated.
Other options could be considered for "marketing" purposes, including variable electricity rates,  and that would seem to be beyond just proving the hardware at this point.
Can you re-phrase this to be clear about what your technical issues is. 
If your issue is that you can only implement one current sensor for ....., then its better to state the reason, and then technically how the system still works.
